[project]
name = "whisper-tube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.11.5",
    "certifi",
    "torch",
    "pytubefix",
    "transformers"
]
